### ISSUE TITLE
Add mesh support

### ISSUE THREAD

**Issue by dj-fiorex** [ezcGman/lora-gateway#1]
Hello, first of all congratulations for the beautiful project! I'm working with esp and lora too for one of my projects and i saw this project. Did you ever think about the ability to add "mesh" support? Ex. one esp32 (call it ESP1) is 1 km far from a wifi connection but another esp32 (ESP2) is connected to a wifi connection and with LoRa it can receive the packets from ESP1 
I hope I was clear, sorry for my  bad english

**Comment by ezcGman** [comment]
Heyhey,

first: I'M TERRIBLY SORRY for the late answer!!
Second: Thanks for the nice words!! <3

On your question: I actually did not, no :) Hrrmmm... I mean, your described scenario is more a repeater scenario. A mesh is a bit more complex and allows for dynamically adding and removing of gateways... Bur I get your point... Let me think about that a bit! I try coming back to you tomorrow!

Greetings and thanks for the great idea,

Andy!

**Comment by ezcGman** [comment]
Oh god, I never replied here... I'm a terrible person xD

Quick answer, as you guessed: I have not planned this just yet, just way too many projects. I still like the idea and may one day do that, when I need to send these over longer distances...

Thanks again for the idea and sorry again for no-reply here...
