### ISSUE TITLE
Is the sender different code?

### ISSUE THREAD

**Issue by theswink** [ezcGman/lora-gateway#2]
Hi Andy,
Thanks for this beautiful piece of code. I have a probably dumb question. Is the Sender code the same as the gateway code?
Or is there sender code somewhere I didn't look well enough for? I saw the code to share between gateway and sender, but no separate sender code.

**Comment by ezcGman** [comment]
Heyhey,

thanks for the beautiful words <3

There is indeed a piece of explanation and examples here: https://github.com/ezcGman/lora-gateway#how-can-i-actually-send-messages

Let me know if that helps (or not ;) )!

Greetings,

Andy!
