### ISSUE TITLE
ttgo lora 32 or Heltec ESP32 Lora

### ISSUE THREAD

**Issue by starfish1107** [ezcGman/lora-gateway#4]
will this sketch also work with ttgo lora 32 or Heltec ESP32 Lora?

**Comment by nikito7** [comment]
You need to change pins.

It should work 

https://github.com/ezcGman/lora-gateway/blob/282f90c1941ce687d1f0692d93f1a7b4fd7a3eef/src/lora-gateway-e32/lora-gateway-e32.ino#L239

And something here:

https://github.com/ezcGman/lora-gateway/blob/282f90c1941ce687d1f0692d93f1a7b4fd7a3eef/src/lora-gateway-e32/lora-gateway-e32.ino#L32

In arduino ide just select correct board

**Comment by ezcGman** [comment]
So sorry for the late response! I had my notifications turned off... fixed it! And thanks to Nikito! I expect it to be solved, so closing! Pls re-open, if u still have issues
